# Generated by Django 4.1.6 on 2023-06-29 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('correos', '0001_initial'),
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enviados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correos.correos')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantillas.plantillas')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
