# Generated by Django 4.1.6 on 2023-06-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillas',
            name='redireccion',
        ),
    ]
