# Generated by Django 4.1.6 on 2023-06-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0003_script_alter_plantillas_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Script',
        ),
    ]
