# Generated by Django 4.1.6 on 2023-06-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0004_delete_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillas',
            name='script',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
