# Generated by Django 4.1.6 on 2023-06-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0005_plantillas_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillas',
            name='icono',
            field=models.ImageField(default=1, upload_to='imagenes'),
            preserve_default=False,
        ),
    ]
