# Generated by Django 4.1.6 on 2023-06-29 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smtp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus_Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agente', models.TextField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo', models.CharField(blank=True, max_length=10, null=True)),
                ('parametros', models.TextField(blank=True, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('idioma', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('enviado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smtp.enviados')),
            ],
        ),
        migrations.CreateModel(
            name='Estatus_PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agente', models.TextField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo', models.CharField(blank=True, max_length=10, null=True)),
                ('parametros', models.TextField(blank=True, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('idioma', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('enviado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smtp.enviados')),
            ],
        ),
        migrations.CreateModel(
            name='Estatus_Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agente', models.TextField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo', models.CharField(blank=True, max_length=10, null=True)),
                ('parametros', models.TextField(blank=True, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('idioma', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('enviado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smtp.enviados')),
            ],
        ),
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=25)),
                ('contraseña', models.CharField(max_length=25)),
                ('estatus_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registradores.estatus_web')),
            ],
        ),
    ]
